Pokeapp/Pokeapp/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')), 
    path('accounts/', include('django.contrib.auth.urls')),
]

Pokeapp/app/urls.py
from django.urls import path
from .views import Index, RegistroEntrenador,registroMaquina,Pokemones,Battle, Historial, pokeCambio,verMaquinas,Home

app_name = 'app'
urlpatterns = [
    path('', Index, name="Index"),
    path('RegistroEntrenador', RegistroEntrenador, name= "RegistroEntrenador"),
    path('registroMaquina', registroMaquina, name= "registroMaquina"),
    path('Pokemones-<id>', Pokemones, name= "Pokemones"),
    path('Battle-<id>', Battle, name= "Battle"),
    path('Historial-<id>', Historial, name= "Historial"),
    path('pokeCambio-<id>', pokeCambio, name= "pokeCambio"),
    path('pokeCambio', pokeCambio, name= "pokeCambio"),
    path('verMaquinas', verMaquinas, name= "verMaquinas"),
    path('Home-<id>', Home, name= "Home"),
    
    
]

Pokeapp/app/templates/app/base.html
{% load static %} 
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!-- ===== BOX ICONS ===== -->
        <link href='https://cdn.jsdelivr.net/npm/boxicons@2.0.5/css/boxicons.min.css' rel='stylesheet'>
        <script src="https://code.iconify.design/2/2.1.0/iconify.min.js"></script>
        <!-- ===== CSS ===== -->
        
        {% block css %}
        {%if equipo == 1%}
        <link rel="stylesheet" href="{% static 'app/css/instinto.css' %}">
        {%elif equipo == 2%}
        <link rel="stylesheet" href="{% static 'app/css/mistico.css' %}">
        {%else%}
        <link rel="stylesheet" href="{% static 'app/css/valor.css' %}">
        {%endif%}
        {% endblock %} 
        
        {% block title %}

        {% endblock %} 

    </head>
    
 <body>
     
 </body>
        

        
            {% block body %}
            
            {% endblock %} 
       
        
        
        {% block js %}
        
        {% endblock %} 
   
</html>

Pokeapp/app/templates/app/battle.html
{% extends 'app/Base.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    {% block css %}
    <a href="https://icons8.com/icon/ZrM1LKamqXR8/health"></a>
    <link rel="stylesheet" href="{% static 'app/css/battle.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    
        {%if equipo == 1%}
        <link rel="stylesheet" href="{% static 'app/css/instinto.css' %}">
        {%elif equipo == 2%}
        <link rel="stylesheet" href="{% static 'app/css/mistico.css' %}">
        {%else%}
        <link rel="stylesheet" href="{% static 'app/css/valor.css' %}">
        {%endif%}
    {% endblock %}
    
    {% block title %}
    <title>Batalla</title>
    {% endblock %} 

</head>

{% block body %}
<body id="body" background="{% static 'app/img/fondooR.jpg'   %}">
    
    <div class="l-navbar" id="nav-bar">
        <nav class="nav" >
            
            <div > 
                <div id="header-toggle" >
                    <a href="#" class="nav__logo" >
                        <i class='bx bx-layer nav__logo-icon' ></i>
                        <span class="nav__logo-name" >Menú</span>
                    </a>
                </div>
                

                <div class="nav__list">
                    <a href="{% url 'app:Home' usuario.id %}" class="nav__link">
                        <i class='bx bx-user nav__icon' ></i>
                        <span class="nav__name">Perfil</span>
                    </a>
                    
                    <a href="{% url 'app:Pokemones' usuario.id %}" class="nav__link">
                        <span class="iconify nav__icon" data-icon="mdi:pokeball">Pokemon</span>
                        <span class="nav__name">Pokemon</span>
                    </a>
                    
                    <a href="{% url 'app:Battle' usuario.id %}" class="nav__link active">
                        <span class="iconify nav__icon" data-icon="ri:sword-line"></span>
                        <span class="nav__name">Duelo</span>
                    </a>

                    <a href="{% url 'app:Historial' usuario.id %}" class="nav__link">
                        <span class="iconify nav__icon" data-icon="la:trophy"></span>
                        <span class="nav__name">Historial Batallas</span>
                    </a>
                </div>
            </div>

            <a href="{% url 'logout' %}" class="nav__link">
                <i class='bx bx-log-out nav__icon' ></i>
                <span class="nav__name">Cerrar Sesión</span>
            </a>
        </nav>
    </div>

    
     
    <div id="juego"> 
        <h2 id="mName" class="text-left">{{maquina.userName}}</h2>
        <img class="sobre" src="{% static 'app/img/Battle/basePokemon2.png' %}"  id="base2">
        <img class="balls1" src="{% static 'app/img/Battle/pokeleft.png' %}"  > 
        <img class="poke1" src="{{Mp1.img}}" id="m1" > 
        <img class="poke1" src="{{Mp2.img}}" id="m2" > 
        <img class="poke1" src="{{Mp3.img}}" id="m3" > 
        <img class="poke1" src="{{Mp4.img}}" id="m4" > 
        <img class="poke1" src="{{Mp5.img}}" id="m5" > 
        <img class="poke1" src="{{Mp6.img}}" id="m6" > 

        <audio id ="audio" autoplay loop>
            <source src="{% static 'app/sound/BattleRuby2.mp3' %}" type="audio/mpeg">
        </audio>
        
        <div class="   col-4 p-2" id="play">
            <div class="col">
                <div class="row">
                    <div class="col">
                        
                        <input type="text" class="d1 text-center" id="j1"> 
                    </div>
                    <div class="col mt-2">
                        <img class="poke1" src="{% static 'app/img/Battle/vs.png' %}" id="vs"> 
                    </div>
                    <div class="col"> 
                        
                        <input type="text" class="d1 text-center" id="j2">
                    </div>
                    
                </div>
                <div class="row mt-3  mx-auto col-8">
                    <button onclick="juego()" class="btn btn-primary btn-sm btn-block" id="empezar">Pelear</button>
                    <button onclick="Siguiente()" class="btn btn-primary btn-sm btn-block" id="siguiente">Siguiente</button>
                </div>
                <div class="col   border-dark mt-2"> 
                    <h2 id="win" class="text-center">WIN</h2>
                </div>
            </div>
            
        </div>
        <h2 id="jName" class="text-left">{{usuario.userName}} </h2>
        <img class="sobre2" src="{% static 'app/img/Battle/basePokemon1.png' %}"  id="base1">
        <img class="balls2" src="{% static 'app/img/Battle/pokeright.png' %}"   >
        <img class="poke2" src="{{Jp1.img}}" id="p1"  > 
        <img class="poke2" src="{{Jp2.img}}" id="p2" > 
        <img class="poke2" src="{{Jp3.img}}" id="p3" > 
        <img class="poke2" src="{{Jp4.img}}" id="p4" > 
        <img class="poke2" src="{{Jp5.img}}" id="p5" > 
        <img class="poke2" src="{{Jp6.img}}" id="p6" > 
    </div>

    
    <div class="card  col-4 p-2" id="dificultad">
        <h1 class="text-center">Batalla</h1>
        <h4 class="text-center">Elige la dificultad</h4>
        <form  method="GET" class="text-center">
            <select id="dif" name="Buscar" value = "{{request.GET.Buscar}}" > 
                <option value="1">Lider de Gimnasio</option>
                <option value="2">Alto Mando</option>
                <option value="3">Campeón</option>  
            </select> 
        </form>
        <button id="jugar"  class=" btn btn-danger btn-block mt-2">Jugar</button>
    </div>  
    
    <div class="col-12  mt-4">
        
        <form method="POST" > 
            <div id="FTerminar">
                {% csrf_token %} 
                {{form.Estado}} 
                {{form.Dificultad}} 
                {{form.img_maquina}} 
                {{form.Name_maquina}} 
        
            </div>  
            <button type="submit" id="Terminar" class="btn btn-danger border-dark">Terminar</button>
        </form>
        <p id="img">{{maquina.img}}</p>
    </div>
    <div>
        <h4 id="final" class="text-center">Final</h4>
    </div>
    {%block js%}
    <script src="{% static 'app/js/battle.js'%}"></script>
    {% endblock %}

    
</body>
{% endblock %} 
</html>

Pokeapp/app/templates/app/dificultad.html
{% extends 'app/Base.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    {% block css %}
    <a href="https://icons8.com/icon/ZrM1LKamqXR8/health"></a>
    <link rel="stylesheet" href="{% static 'app/css/battle.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    
    {%if equipo == 1%}
    <link rel="stylesheet" href="{% static 'app/css/instinto.css' %}">
    {%elif equipo == 2%}
    <link rel="stylesheet" href="{% static 'app/css/mistico.css' %}">
    {%else%}
    <link rel="stylesheet" href="{% static 'app/css/valor.css' %}">
    {%endif%}
    {% endblock %}
    
    {% block title %}
    <title>Batalla</title>
    {% endblock %} 

</head>

{% block body %}
<body id="body" background="{% static 'app/img/fondooR.jpg'   %}">
    
    <div class="l-navbar" id="nav-bar">
        <nav class="nav" >
            
            <div > 
                <div id="header-toggle" >
                    <a href="#" class="nav__logo" >
                        <i class='bx bx-layer nav__logo-icon' ></i>
                        <span class="nav__logo-name" >Menú</span>
                    </a>
                </div>
                

                <div class="nav__list">
                    <a href="{% url 'app:Home' usuario.id %}" class="nav__link">
                        <i class='bx bx-user nav__icon' ></i>
                        <span class="nav__name">Perfil</span>
                    </a>
                    
                    <a href="{% url 'app:Pokemones' usuario.id %}" class="nav__link">
                        <span class="iconify nav__icon" data-icon="mdi:pokeball">Pokemon</span>
                        <span class="nav__name">Pokemon</span>
                    </a>
                    
                    <a href="" class="nav__link active">
                        <span class="iconify nav__icon" data-icon="ri:sword-line"></span>
                        <span class="nav__name">Duelo</span>
                    </a>

                    <a href="{% url 'app:Historial' usuario.id %}" class="nav__link">
                        <span class="iconify nav__icon" data-icon="la:trophy"></span>
                        <span class="nav__name">Historial Batallas</span>
                    </a>
                </div>
            </div>

            <a href="{% url 'logout' %}" class="nav__link">
                <i class='bx bx-log-out nav__icon' ></i>
                <span class="nav__name" >Cerrar Sesión</span>
            </a>
        </nav>
    </div>

    
    <div class="card bg-light border-dark col-4 p-2" id="dificultad">
        <h1>Batalla</h1>
        <h4>Elige la dificultad</h4>
        <form  method="GET" >
            <select id="dif" name="Buscar">
                <option value="1">Lider de Gimnasio</option>
                <option value="2">Alto Mando</option>
                <option value="3">Campeón</option>  
            </select>
            <button type="submit" id="jugar" href="{% url 'app:Battle' usuario.id %}">Jugar</button>
        </form>
    </div>
    
    
    {%block js%}
    <script src="{% static 'app/js/battle.js'%}"></script>
    {% endblock %}

</body>
{% endblock %} 
</html>

Pokeapp/app/templates/app/home.html
{% extends 'app/Base.html' %}
{% load static %}
   
    {% block css %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <a href="https://icons8.com/icon/ZrM1LKamqXR8/health"></a>
    {%if equipo == 1%}
    <link rel="stylesheet" href="{% static 'app/css/instinto.css' %}">
    {%elif equipo == 2%}
    <link rel="stylesheet" href="{% static 'app/css/mistico.css' %}">
    {%else%}
    <link rel="stylesheet" href="{% static 'app/css/valor.css' %}">
    {%endif%}
    {% endblock %} 

    {% block title %}
    <title>Poke-Home</title>
    {% endblock %} 
    
     
    {% block body %}
    <!--fondo--->
    <body id="body-pd" > 
    <div class="l-navbar" id="nav-bar">
        <nav class="nav" >
            
            <div > 
                <div id="header-toggle" >
                    <a href="#" class="nav__logo" >
                        <i class='bx bx-layer nav__logo-icon' ></i>
                        <span class="nav__logo-name" >Menú</span>
                    </a>
                </div>
                

                <div class="nav__list">
                    <a href="{% url 'app:Home' usuario.id %}" class="nav__link active">
                        <i class='bx bx-user nav__icon' ></i>
                        <span class="nav__name">Perfil</span>
                    </a>
                    
                    <a href="{% url 'app:Pokemones' usuario.id %}" class="nav__link">
                        <span class="iconify nav__icon" data-icon="mdi:pokeball">Pokemon</span>
                        <span class="nav__name">Pokemon</span>
                    </a>
                    
                    <a href="{% url 'app:Battle' id %}" class="nav__link">
                        <span class="iconify nav__icon" data-icon="ri:sword-line"></span>
                        <span class="nav__name">Duelo</span>
                    </a>

                    <a href="{% url 'app:Historial' usuario.id %}" class="nav__link">
                        <span class="iconify nav__icon" data-icon="la:trophy"></span>
                        <span class="nav__name">Historial Batallas</span>
                    </a>
                </div>
            </div>

            <a href="{% url 'logout' %}" class="nav__link">
                <i class='bx bx-log-out nav__icon' ></i>
                <span class="nav__name">Cerrar Sesión</span>
            </a>
        </nav>
    </div>
    
        <div class="row" >
            <div class="col-4 mt-5">
                <div class="card bg-light border-dark "> 
                    <div class="card-body">
                        <div>
                            <img src="{{usuario.img}}" class = "rounded-circle d-block w-50 mx-auto"  alt="">
                            <h2 class="card-tittle">Nombre de Usuario</h2>
                            {{usuario.userName}} 
                        </div>
                        
                        <div>
                            <h2>Genero</h2>
                            {% if genero == 1 %} 
                            Hombre 
                            {% else %} 
                            Mujer
                            {% endif %} 
                        </div>
                        <div>
                            <h2>Equipo</h2>
                                {% if equipo == 1 %} 
                                Instinto
                                {% elif equipo == 2 %} 
                                Mistico
                                {% else %} 
                                valor
                                {% endif %} 
                                </div>
                        </div> 
                    </div>
                </div>

                <div class="col-8" >
                    <div class="row">
                           {% for poke in pokemons%}
                                <div class="col-4 mt-4 ">
                                    <div class="card bg-light border border-dark">
                                        <div class="card-header bg-transparent border-dark">
                                            <h4 class="card-title text-center">{{poke.pokenombre}}</h4> 
                                        </div>
                                        <img class="card-img mx-auto" src="{{poke.img}}" alt=""  style="width: 18rem;">
    
                                        <div class="card-footer bg-transparent  border-dark">
                                            <div class="row">
                                                <div class="col-4">
                                                    <span class="iconify" data-icon="whh:lifeempty"></span>{{poke.vida}}
                                                </div>
                                                <div class="col-4">
                                                    <span class="iconify" data-icon="akar-icons:shield"></span>{{poke.defensa}}
                                                </div>
                                                <div class="col-4">
                                                    <span class="iconify" data-icon="akar-icons:sword"></span>{{poke.ataque}}
                                                </div>
                                            </div>
                                        </div>
                                        
                                    </div>
                                </div>               
                            {%endfor%} 
                               
                        
                    </div>
                    
                </div>
            </div>

            

        
    </div>
    {%block js%}
    <script src="{% static 'app/js/nav.js'%}"></script>
    {% endblock %}
</body>      
    {% endblock %} 

Pokeapp/app/templates/app/index.html
{% extends 'app/Base.html' %}
{% load static %}
   
    {% block css %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <a href="https://icons8.com/icon/ZrM1LKamqXR8/health"></a>
    {%if equipo == 1%}
    <link rel="stylesheet" href="{% static 'app/css/instinto.css' %}">
    {%elif equipo == 2%}
    <link rel="stylesheet" href="{% static 'app/css/mistico.css' %}">
    {%else%}
    <link rel="stylesheet" href="{% static 'app/css/valor.css' %}">
    {%endif%}
    {% endblock %} 

    {% block title %}
    <title>Poke-Home</title>
    {% endblock %} 
    
     
    {% block body %}
    <!--fondo--->
    <body id="body-pd" > 
    <div class="l-navbar" id="nav-bar">
        <nav class="nav" >
            
            <div > 
                <div id="header-toggle" >
                    <a href="#" class="nav__logo" >
                        <i class='bx bx-layer nav__logo-icon' ></i>
                        <span class="nav__logo-name" >Menú</span>
                    </a>
                </div>
                

                <div class="nav__list">
                    <a href="{% url 'app:Home'  id %}" class="nav__link active">
                        <i class='bx bx-user nav__icon' ></i>
                        <span class="nav__name">Perfil</span>
                    </a>
                    
                    <a href="{% url 'app:Pokemones' id %}" class="nav__link">
                        <span class="iconify nav__icon" data-icon="mdi:pokeball">Pokemon</span>
                        <span class="nav__name">Pokemon</span>
                    </a>
                    
                    <a href="{% url 'app:Battle' id %}" class="nav__link ">
                        <span class="iconify nav__icon" data-icon="ri:sword-line"></span>
                        <span class="nav__name">Duelo</span>
                    </a>

                    <a href="{% url 'app:Historial' id %}" class="nav__link">
                        <span class="iconify nav__icon" data-icon="la:trophy"></span>
                        <span class="nav__name">Historial Batallas</span>
                    </a>
                    
                </div>
            </div>

            <a href="{% url 'logout' %}" class="nav__link">
                <i class='bx bx-log-out nav__icon' ></i>
                <span class="nav__name">Cerrar Sesión</span>
            </a>
        </nav>
    </div>
    
        <div class="row" >
            <div class="col-4 mt-5">
                <div class="card bg-light border-dark "> 
                    <div class="card-body">
                        <div>
                            <img src="{{usuario.img}}" class = "rounded-circle d-block w-50 mx-auto"  alt="">
                            <h2 class="card-tittle">Nombre de Usuario</h2>
                            {{usuario.userName}} 
                        </div>
                        
                        <div>
                            <h2>Genero</h2>
                            {% if genero == 1 %} 
                            Hombre 
                            {% else %} 
                            Mujer
                            {% endif %} 
                        </div>
                        <div>
                            <h2>Equipo</h2>
                                {% if equipo == 1 %} 
                                Instinto
                                {% elif equipo == 2 %} 
                                Mistico
                                {% else %} 
                                valor
                                {% endif %} 
                                </div>
                        </div> 
                    </div>
                </div>

                <div class="col-8" >
                    <div class="row">
                           {% for poke in pokemons%}
                                <div class="col-4 mt-4 ">
                                    <div class="card bg-light border border-dark">
                                        <div class="card-header bg-transparent border-dark">
                                            <h4 class="card-title text-center">{{poke.pokenombre}}</h4> 
                                        </div>
                                        <img class="card-img mx-auto" src="{{poke.img}}" alt=""  style="width: 18rem;">
    
                                        <div class="card-footer bg-transparent  border-dark">
                                            <div class="row">
                                                <div class="col-4">
                                                    <span class="iconify" data-icon="whh:lifeempty"></span>{{poke.vida}}
                                                </div>
                                                <div class="col-4">
                                                    <span class="iconify" data-icon="akar-icons:shield"></span>{{poke.defensa}}
                                                </div>
                                                <div class="col-4">
                                                    <span class="iconify" data-icon="akar-icons:sword"></span>{{poke.ataque}}
                                                </div>
                                            </div>
                                        </div>
                                        
                                    </div>
                                </div>               
                            {%endfor%} 
                               
                        
                    </div>
                    
                </div>
            </div>

            

        
    </div>
    {%block js%}
    <script src="{% static 'app/js/nav.js'%}"></script>
    {% endblock %}
</body>      
    {% endblock %} 

Pokeapp/app/templates/app/pokeHistorial.html
{% extends 'app/Base.html' %}
{% load static %}
   
    {% block css %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <a href="https://icons8.com/icon/ZrM1LKamqXR8/health"></a>

    <link rel="stylesheet" href="{% static 'app/css/Historial.css' %}">
    {%if equipo == 1%}
    <link rel="stylesheet" href="{% static 'app/css/instinto.css' %}">
    {%elif equipo == 2%}
    <link rel="stylesheet" href="{% static 'app/css/mistico.css' %}">
    {%else%}
    <link rel="stylesheet" href="{% static 'app/css/valor.css' %}">
    {%endif%}
    {% endblock %} 

    {% block title %}
    <title>PokeMones</title>
    {% endblock %} 
    
     
    {% block body %}
    <!--fondo--->
    <body id="body-pd" > 
    <div class="l-navbar" id="nav-bar">
        <nav class="nav" >
            
            <div > 
                <div id="header-toggle" >
                    <a href="#" class="nav__logo" >
                        <i class='bx bx-layer nav__logo-icon' ></i>
                        <span class="nav__logo-name" >Menú</span>
                    </a>
                </div>
                

                <div class="nav__list">
                    <a href="{% url 'app:Home' id %}" class="nav__link">
                        <i class='bx bx-user nav__icon' ></i>
                        <span class="nav__name">Perfil</span>
                    </a>
                    
                    <a href="{% url 'app:Pokemones' id %}" class="nav__link">
                        <span class="iconify nav__icon" data-icon="mdi:pokeball">Pokemon</span>
                        <span class="nav__name">Pokemon</span>
                    </a>
                    
                    <a href="{% url 'app:Battle' id %}" class="nav__link">
                        <span class="iconify nav__icon" data-icon="ri:sword-line"></span>
                        <span class="nav__name">Duelo</span>
                    </a>

                    <a href="{% url 'app:Historial' id %}" class="nav__link active">
                        <span class="iconify nav__icon" data-icon="la:trophy"></span>
                        <span class="nav__name">Historial Batallas</span>
                    </a>
                </div>
            </div>

            <a href="{% url 'logout' %}" class="nav__link">
                <i class='bx bx-log-out nav__icon' ></i>
                <span class="nav__name">Cerrar Sesión</span>
            </a>
        </nav>
    </div>
    <audio id ="audio" autoplay loop>
        <source src="{% static 'app/sound/Ruby2.mp3' %}" type="audio/mpeg">
        
    </audio>

        <div class="  ">
            <h1 class="text-center mt-4">Historial de batallas</h1>
            <div class="col-8 "> 
                <div class="col">
                    {% for batalla in batallas  %}
                        <div class="row" >
                            <div class="card mt-4" id="card"> 
                                <div class="col">
                                    <div class="row">
                                        <div class="col-4">
                                            <img class="card-img mx-auto" src="{{batalla.img_maquina}}" alt=""  style="width: 12rem; height:12rem;">
                                        </div> 
                                        <div class="col">
                                            <div class="row"> 
                                                <div class="col" id="nombre"> 
                                                    
                                                    <div class="col">
                                                        <div class="row">
                                                            <h3 class="card-title text-center mt-5">Contrincante:</h3> 
                                                        </div>
                                                        <div class="row">
                                                            <h4 class="card-title text-center">{{batalla.Name_maquina}}</h5> 
                                                        </div>
                                                    </div> 
                                                    
                                                </div>
                                                <div class="  col" id="dificultad">
                                                    <div class="row">
                                                        <h3 class="card-title text-center mt-5">Dificultad:</h3> 
                                                    </div>
                                                    <div class="row">
                                                        <h4 class="card-title text-center">{{batalla.Dificultad}}</h4></div>
                                                    </div>
                                                <div class="col resultado">
                                                    <div class="row"> 
                                                        <h4 class="card-title text-center mt-5">Resultado:</h4> 
                                                    </div>
                                                    <div class="row"> 
                                                        {% if batalla.Estado == 'VICTORY'  %}
                                                            <img class="card-img" src="{% static 'app/img/estados/1.jpg'   %}" alt="image"  >
                                                        {% elif batalla.Estado == 'LOSE' %}
                                                            <img class="card-img  " src="{% static 'app/img/estados/2.jpg'   %}" alt="image"  >
                                                        {% else %}
                                                            <img class="card-img  " src="{% static 'app/img/estados/3.jpg'   %}" alt="image"  >
                                                        {% endif %}
                                                    </div>
                                                        
                                                </div>
                                            </div>
                                        </div>
                                    </div> 
                                     
                                </div> 
                            </div>
                        </div>
                    {% endfor %}   
                </div> 
            </div> 
    </div>
    {%block js%}
    <script src="{% static 'app/js/nav.js'%}"></script>
    {% endblock %}
</body>      
    {% endblock %} 